/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.dao.ProdutoDAO;


public class Home extends javax.swing.JFrame {

    private ProdutoDAO produtoDAO;
    private DefaultTableModel tbprodutos;
    private List<Produto> listaProdutos;
    
    public Home() {
        initComponents();
         produtoDAO = new ProdutoDAO();
        tbprodutos = (DefaultTableModel) jvprodutos.getModel();
         listaProdutos = new ArrayList<>(); // Inicializando a lista de produtos
        listarProdutos();
    }
    
  private void listarProdutos() {
    tbprodutos.setRowCount(0); // Limpa a tabela antes de adicionar os dados
    try {
        listaProdutos = produtoDAO.read(); // Obtém a lista de produtos do banco de dados
        for (Produto p : listaProdutos) {
            Object[] dados = {p.getDescricaoProduto(), p.getPreco(), p.getNumeroContato()};
            tbprodutos.addRow(dados);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao listar produtos: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jvdescricao = new javax.swing.JTextField();
        jvpreco = new javax.swing.JTextField();
        jvnumero = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jvprodutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro De Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel2.setText("DESCRIÇÃO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 220, 80, 40);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel3.setText("PREÇO (R$)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 230, 80, 20);

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel4.setText("NÚMERO DE CONTATO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 230, 150, 20);
        getContentPane().add(jvdescricao);
        jvdescricao.setBounds(290, 250, 140, 30);

        jvpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvprecoActionPerformed(evt);
            }
        });
        getContentPane().add(jvpreco);
        jvpreco.setBounds(470, 250, 150, 30);

        jvnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvnumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jvnumero);
        jvnumero.setBounds(640, 250, 160, 30);

        jToggleButton1.setBackground(new java.awt.Color(204, 255, 204));
        jToggleButton1.setText("Cadastrar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(290, 310, 100, 23);

        jToggleButton3.setBackground(new java.awt.Color(204, 255, 204));
        jToggleButton3.setText("Alterar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(410, 310, 100, 23);

        jToggleButton4.setBackground(new java.awt.Color(204, 255, 204));
        jToggleButton4.setText("Excluir");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(530, 310, 90, 23);

        jvprodutos.setBackground(new java.awt.Color(204, 255, 204));
        jvprodutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jvprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "DESCRIÇÃO", "PREÇO R$", "NÚMERO DE CONTATO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jvprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jvprodutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jvprodutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 360, 1010, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/N.E.S (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1300, 710);

        setSize(new java.awt.Dimension(1327, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // Botão Cadastrar
    Produto p = new Produto();
    p.setDescricaoProduto(jvdescricao.getText());
    p.setPreco(Double.parseDouble(jvpreco.getText()));
    p.setNumeroContato(jvnumero.getText()); // Aqui, jvnumero.getText() retorna uma String
    
    try {
        produtoDAO.create(p);
        
        limparCampos();
        listarProdutos(); // Atualiza a tabela após cadastrar
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto: " + e.getMessage());
    }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       // Botão Excluir
        if (jvprodutos.getSelectedRow() != -1) {
            Produto p = listaProdutos.get(jvprodutos.getSelectedRow());
            
            try {
                produtoDAO.delete(p);
                
                limparCampos();
                listarProdutos(); // Atualiza a tabela após excluir
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir produto: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }
        
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jvprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jvprodutosMouseClicked
        // Quando clicar na tabela de produtos
        if (jvprodutos.getSelectedRow() != -1) {
            Produto p = listaProdutos.get(jvprodutos.getSelectedRow());
            jvdescricao.setText(p.getDescricaoProduto());
            jvpreco.setText(String.valueOf(p.getPreco()));
            jvnumero.setText(String.valueOf(p.getNumeroContato()));
        }
        
    }//GEN-LAST:event_jvprodutosMouseClicked

    private void limparCampos() {
        jvdescricao.setText("");
        jvpreco.setText("");
        jvnumero.setText("");
    }
    
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // Botão Alterar
    if (jvprodutos.getSelectedRow() != -1) {
        Produto p = new Produto();
        p.setDescricaoProduto(jvdescricao.getText());
        p.setPreco(Double.parseDouble(jvpreco.getText()));
        p.setNumeroContato(jvnumero.getText()); // Aqui também, jvnumero.getText() retorna uma String
        
        try {
            p.setId(listaProdutos.get(jvprodutos.getSelectedRow()).getId()); // Obtém o ID do produto selecionado
            produtoDAO.update(p);
            
            limparCampos();
            listarProdutos(); // Atualiza a tabela após alterar
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar produto: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecione um produto para alterar!");
    }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jvprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvprecoActionPerformed

    private void jvnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvnumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField jvdescricao;
    private javax.swing.JTextField jvnumero;
    private javax.swing.JTextField jvpreco;
    private javax.swing.JTable jvprodutos;
    // End of variables declaration//GEN-END:variables

    
}
